name: demo-release
version: "1"
summary: A qt qml app snap
description: |
  This snap provides a Qt/qml app that displays a different gif with each revision. 
  The purpose is to visually demonstrate release of a new revision to channel
  and the subsequent change on the running client. The snap depends on test-qt-platform
  snap to provide Qt. It is intented to be used with ubuntu-frame snap on Ubuntu Core. 
confinement: strict
base: core20
grade: stable

plugs:
  network:
  opengl:
  wayland:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20
  qt-platform:
    interface: content
    content: qt-platform
    target: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  fonts-etc:
    interface: content
    content: fonts-etc
    target: $SNAP_DATA/etc/fonts
  fonts:
    interface: content
    content: fonts-usr-share
    target: $SNAP/usr/share/fonts
  qml:
    interface: content
    content: qml
    target: $SNAP/qmlscene
  glvnd:
    interface: content
    content: glvnd
    target: $SNAP/usr/share/glvnd

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: daemon.sh
  echo:
    command: echo.sh

environment:
  QT_QPA_PLATFORM: wayland
  # find font config (as provided through content share)
  FONTCONFIG_FILE: $SNAP_DATA/etc/fonts/fonts.conf
  FONTCONFIG_PATH: $SNAP_DATA/etc/fonts
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/arm-linux-gnueabihf
  # find mesa impl of gl from content provdier (https://www.mesa3d.org/envvars.html)
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  # find EGL from content provider (https://www.mesa3d.org/egl.html
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts:
    bind: $SNAP/usr/local/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  app:
    plugin: dump
    source: app

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland

  launchers:
    source: launchers
    plugin: dump
